{application,mongodb_ecto,
             [{applications,[kernel,stdlib,elixir,ecto,mongodb,logger]},
              {description,"MongoDB adapter for Ecto\n"},
              {modules,['Elixir.Mongo.Ecto','Elixir.Mongo.Ecto.ChangeArray',
                        'Elixir.Mongo.Ecto.ChangeMap',
                        'Elixir.Mongo.Ecto.Connection',
                        'Elixir.Mongo.Ecto.Conversions',
                        'Elixir.Mongo.Ecto.Helpers',
                        'Elixir.Mongo.Ecto.NormalizedQuery',
                        'Elixir.Mongo.Ecto.NormalizedQuery.AggregateQuery',
                        'Elixir.Mongo.Ecto.NormalizedQuery.CommandQuery',
                        'Elixir.Mongo.Ecto.NormalizedQuery.CountQuery',
                        'Elixir.Mongo.Ecto.NormalizedQuery.ReadQuery',
                        'Elixir.Mongo.Ecto.NormalizedQuery.WriteQuery',
                        'Elixir.Mongo.Ecto.Regex','Elixir.Mongo.Ecto.Utils']},
              {registered,[]},
              {vsn,"0.2.1"}]}.
